name: Android Compatiblity Tests

on:
  # Nightly builds to ensure dependencies don't break anything
  schedule:
    - cron: '0 0 * * *'

jobs:
  android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          emulator-build: 7425822 # to fix newest issue
          script: ./gradlew connectedAndroidTest -Pandroid.useAndroidX=true --info
